name: PR Review with GPTScript

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pr_review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get PR Details
      id: pr_details
      run: |
        PR_URL=$(jq -r '.pull_request.html_url' $GITHUB_EVENT_PATH)
        PR_NUMBER=$(jq -r '.pull_request.number' $GITHUB_EVENT_PATH)
        PR_FILES=$(jq -r '.pull_request.changed_files' $GITHUB_EVENT_PATH)
        echo "PR_URL=${PR_URL}" >> $GITHUB_ENV
        echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_ENV
        echo "PR_FILES=${PR_FILES}" >> $GITHUB_ENV

    - name: Install GPTScript
      run: curl https://get.gptscript.ai/install.sh | sh

    - name: Run GPTScript for Code Review
      id: run_gptscript
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        REVIEW_COMMENT=$(gptscript codereview.gpt --PR_URL=${{ env.PR_URL }})
        echo "${REVIEW_COMMENT}" > review_comment.md
        
    - name: Post Review Comment
      if: steps.run_gptscript.outputs.review_comment != ''
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        gh pr comment ${{ github.event.pull_request.number }} --body "$(cat review_comment.md)"
        if echo "${REVIEW_COMMENT}" | grep -q "Code: Require Changes"; then
          echo "Code requires changes."
          exit 1  # Fails the workflow if changes are required
        fi
